### ISSUE TITLE
OSError: [Errno 98] Address already in use``

### ISSUE THREAD

**Issue by rapi3** [markv9401/Fake-Gree-server#1]
Hello,
I run the script from crontab on latest ubuntu server:

```@reboot    root    python3 -u /root/fakegree/gree_server.py 192.168.12.28 1812 dis.gree.com > /dev/null 2>&1 &```

Any idea why I got this error:

```Traceback (most recent call last):
  File "/root/fakegree/gree_server.py", line 175, in <module>
    GreeSrv(sys.argv[1], int(sys.argv[2]), sys.argv[3])
  File "/root/fakegree/gree_server.py", line 21, in __init__
    self.serve()
  File "/root/fakegree/gree_server.py", line 40, in serve
    self.srv.bind((self.ip, self.port))
OSError: [Errno 98] Address already in use```

Thank you

**Comment by rowra44** [comment]
Hello,
Yeah, it says it right there. The address is already in use. What that means is that something is already bound to the port you're trying to bind to. Try and check what else may be using that port (or if you're trying to start the server twice?)
Anyhow, it's unrelated to this server / code (other than my lack of proper error handling outside of actual business logic :) )

**Comment by rapi3** [comment]
"After more testing it looks like commands from integration have a long delay or sometime are not executed at all if I run the fake server."
edit:
After some test It look like python script it is killed after I exit terminal...

**Comment by rapi3** [comment]
just to let you know how I solved, _my Gree AC it is already initialized and connected to my wifi using android Gree app and I did not wanted to repeat the steps as I don't have the app installed on phone._

- sniffed dns request used from Gree AC => **eu.dis.gree.com**
- in dns server I override sniffed domain with local IP LAN computer that run python script.
- made python script to run forever when computer boot - **I do not use docker**.
- restarted HA and Gree AC.

_**Now HA integration it work without reinitialize Gree AC wifi using fake server**_
